Nova propriedade para dm_municipio
transparencia-mg/age7 pull request #139
Opened 2022-10-17 20:33 UTC by marci-pires

2022-10-17 20:33 UTC, marci-pires commented
Nova propriedade para dm_municipio

2022-10-19 18:34 UTC, gabrielbdornas requested changes

2022-10-19 18:34 UTC, gabrielbdornas commented on datapackage.yaml
> +    description: Teste Marcela
@marci-pires, sugiro incluirmos um texto verdadeiro na propriedade `description`. O que acha de "Dimensão Município"?

Tentei alterar aqui mas como a branch está em seu repositório não consegui. Você consegue fazer dai, correto?

2022-10-19 20:40 UTC, gabrielbdornas commented
@marci-pires modificações deverão aparecer amanhã (20/10/2022) nos conjuntos

2022-10-19 20:40 UTC, merged